#!/usr/bin/env just --justfile

# Using Just: https://github.com/casey/just?tab=readme-ov-file#installation

# List all of the available commands.
default:
  just --list

# Run the web server
web url='http://localhost:4443/anon':
	pnpm install
	VITE_RELAY_URL="{{url}}" pnpm -r run dev

# Install any dependencies.
install:
	pnpm install

# Run the CI checks
check:
	pnpm install --frozen-lockfile
	pnpm -r run check
	pnpm -r run test

# Automatically fix some issues.
fix:
	pnpm install
	pnpm -r run fix

# Upgrade any tooling
upgrade:
	pnpm self-update
	pnpm -r update
	pnpm -r outdated

# Build the packages
build:
	pnpm install --frozen-lockfile
	pnpm -r run build
